"""Add keycloak_id to users

Revision ID: 510a2c0ceca8
Revises: 
Create Date: 2026-10-09 00:12:18.294488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510a2c0ceca8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keycloak_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_users_keycloak_id', 'users', ['keycloak_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_keycloak_id', 'users', type_='unique')
    op.drop_column('users', 'keycloak_id')
    # ### end Alembic commands ###
